#!/bin/bash -e
# Regen ownCloud MySQL user random password

. /etc/default/inithooks

#INITHOOKS_PATH=/usr/lib/inithooks

PASSWORD=$(mcookie)
CONF_FILE=/var/www/owncloud/config/config.php
VALUE='"dbpassword" => '

cp $CONF_FILE $CONF_FILE.backup
REPLACE=s/${VALUE}.*/${VALUE}"'${PASSWORD}',"/
sed -i "$REPLACE" "$CONF_FILE"

$INITHOOKS_PATH/bin/mysqlconf.py --user=owncloud-usr --pass="$PASSWORD"
#/usr/lib/inithooks/bin/mysqlconf.py --user=owncloud_usr --pass="9b317c5051da1c67860fcb45a30fa8c5"